DROP TABLE IF EXISTS weavers;

CREATE TABLE weavers (
        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        first_name TEXT NOT NULL,
        last_name TEXT NOT NULL,
        email VARCHAR,
        experience_level TEXT NOT NULL,
        loom_type TEXT NOT NULL,
        state TEXT NOT NULL,
        bio TEXT NOT NULL
)