DROP TABLE IF EXISTS projects;

CREATE TABLE projects (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    project_title TEXT NOT NULL,
    project_description TEXT NOT NULL,
    weave_structure TEXT NOT NULL,
    warp_material TEXT NOT NULL,
    warp_size VARCHAR,
    weft_material TEXT NOT NULL,
    weft_size VARCHAR,
    sett INTEGER NOT NULL,
    size_on_loom VARCHAR,
    size_off_loom VARCHAR,
    weaver_id INTEGER REFERENCES weavers(id) ON DELETE CASCADE NOT NULL
)